config-version: 2

name: 'dbt_sample_001'
version: "3.0.0"
require-dbt-version: ">=1.10.13"

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_sample_001'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
asset-paths: ["assets"]
docs-paths: ["docs"] 
snapshot-paths: ["snapshots"]


target-path: "target"  # compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


vars:
  "dbt_date:time_zone": "Europe/London"

  # Canonical low timestamp for "never updated" rows
  # Keep quotes inside the value so it can be used as a SQL literal directly:
  # {{ var('low_date_ts') }}::datetime
  low_date_ts: '1900-01-01 00:00:00'
  # Canonical high timestamp for open-ended rows
  high_date_ts: '9999-12-31 00:00:00'

models:
  dbt_sample_001:      
    01_raw:
      +schema: raw
      +materialized: table
    02_stg:
      +schema: stg
      +materialized: view
    03_det:
      +schema: det
      +materialized: incremental
  # ----------------------------
  # Elementary package models
  # ----------------------------
  # elementary:             #  not supported on duckdb yet
  #   +schema: ctl
  #   +tags: ['observability']
