select
  STORE_CODE        as store_code,
  STORE_NAME        as store_name,
  CHANNEL           as channel,
  ADDRESS_LINE1     as address_line1,
  ADDRESS_LINE2     as address_line2,
  CITY              as city,
  COUNTY            as county,
  POSTCODE          as postcode,
  COUNTRY           as country,
  LATITUDE          as latitude,
  LONGITUDE         as longitude,
  MANAGER_NAME      as manager_name,
  AREA_MANAGER_NAME as area_manager_name,
  STORE_SIZE_SQFT   as store_size_sqft,
  DATE_OPENED       as date_opened,
  DATE_CLOSED       as date_closed,
  TRADING_HOURS     as trading_hours,
  REGION            as region,
  CONCEPT           as concept,
  IS_FLAGSHIP       as is_flagship,
  IS_FRANCHISE      as is_franchise,
  TAX_REGION_CODE   as tax_region_code,
  TIMEZONE          as timezone
from {{ ref('t_raw_stores') }} 