# -------------------------------------------------------------------------------
# Program:        gosales_ci
# Project:        dbt-core-sample-duckdb
# Description:    CI workflow for Python lint/tests + SQLFluff (dbt templater)
# Author:         Manzar Ahmed
# First Created:  Jun 2025
# -------------------------------------------------------------------------------
# Program history:
# -------------------------------------------------------------------------------
# Date        Programmer             Description
# ----------  ---------------------  --------------------------------------------
# 2025-06-25  Manzar Ahmed           v0.01/Initial version for Flake8 & Pylint CI
# -------------------------------------------------------------------------------

name: PURE EVE CONSULTING CI - SQLFluff

on:
  push:
    branches:
      - '**'        # run on main and all feature branches
  pull_request:
    branches:
      - main        # block PRs merging into main if lint fails

jobs:
  sqlfluff-lint:
    name: SQLFluff Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install SQLFluff and dbt (DuckDB)
        run: |
          python -m pip install --upgrade pip
          pip install "sqlfluff==3.*" sqlfluff-templater-dbt
          pip install "dbt-core==1.10.*" "dbt-duckdb==1.10.*"

      - name: Create minimal dbt profile (DuckDB in-memory)
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<'YAML'
          dbt_sample_001:
            target: ci
            outputs:
              ci:
                type: duckdb
                path: ":memory:"
                threads: 4
          YAML

      - name: Install dbt packages (if packages.yml present)
        run: dbt deps || true

      - name: Lint dbt models with SQLFluff (fails on violations)
        env:
          DBT_PROFILES_DIR: ~/.dbt
        run: |
          # Lint all SQL under models/ (adjust paths if needed)
          # Exits non-zero on any violation, which fails the job and blocks the PR
          sqlfluff lint models/ \
            --templater dbt \
            --dialect duckdb \
            --format github-annotation \
            --annotation-level failure \
            --write-output annotations.json

      - name: Annotate PR with SQLFluff output
        if: always()  # still post annotations even if lint step failed
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: "SQLFluff Lint"
          input: "./annotations.json"